### ISSUE TITLE
Allow input dictionary in Floris initialization

### ISSUE THREAD

**Issue by petebachant** [WISDEM/FLORIS#13]
Currently, `Floris` expects a JSON input file path, but if someone wanted to, e.g., run FLORIS in batch mode, do parameter sweeps, etc., it may be useful to define the entire farm within a script. I suggest allowing the exact same parsing as the input file but on a Python dictionary. I'm sure it's already there under the hood since the JSON is read into a dictionary anyway.

**Comment by rafmudaf** [comment]
Fixed by #18
