### ISSUE TITLE
OptModules

### ISSUE THREAD

**Issue by jmora30** [WISDEM/FLORIS#19]
When I want to optimize my model using OptModules, I have to create this object from scratch based on the documentation from github and save it into the floris folder, right?. However, when I try to import the module from my code, for some reason its not finding it and I´m unable to import it. Could you give me a step by step to make this module work?

**Comment by rafmudaf** [comment]
@petebachant's improvements have now been merged into master so this should be resolved. I'm closing this issue but @jmora30 please open it again if this is still a problem for you.
