### ISSUE TITLE
Structure as a typical (installable) Python package

### ISSUE THREAD

**Issue by petebachant** [WISDEM/FLORIS#2]
I recommend creating a `floris` subdirectory (such that the package will be called `floris`), and nesting all modules below that. This will negate the need for the hacking of `sys.path`, e.g.: https://github.com/WISDEM/FLORIS/blob/feature/userAPI/wakes/JensenJimenez.py#L3

After this, a `setup.py` file can be created such that `pip install .` will install `floris` in the user's current Python environment.

The imports in the top level `FLORIS.py` script would then become:

```python
from floris.turbines.NREL5MW import NREL5MW
from floris.wakes.JensenJimenez import JensenJimenez
from floris.models.WakeCombination import WakeCombination
from floris.farms.TwoByTwo import TwoByTwo
from floris.io.InputReader import InputReader
```

**Comment by rafmudaf** [comment]
Thanks for the suggest @petebachant . I've implemented this in commit https://github.com/WISDEM/FLORIS/commit/4c0889ae5035b6b916c69e88dea23a8a1e7bcdb9
