### ISSUE TITLE
Why does farm have a hub_height parameter?

### ISSUE THREAD

**Issue by kilojoules** [WISDEM/FLORIS#20]
```
    def _initial_flowfield(self):
        return self.wind_speed * (self.z / self.hub_height)**self.wind_shear
```

**Comment by kilojoules** [comment]
I expected each turbine top have a different height. What does this farm.hub_height variable mean? This issue came from a discussion with Raf...

**Comment by rafmudaf** [comment]
@kilojoules the farm hub height is used to initialize the flow field:
```
    def initialize_flow_field(self):
        u = self.wind_speed * (self.z / self.hub_height)**self.wind_shear
        v = np.zeros(np.shape(u))
        w = np.zeros(np.shape(u))
        return u, v, w
```

This variable name is misleading so it will be changed in the future.
