### ISSUE TITLE
Turbine.eta...

### ISSUE THREAD

**Issue by rafmudaf** [WISDEM/FLORIS#33]
Is the `eta` property on the Turbine object needed? This is an input to the turbine model in the input file, but it is not actually used in the Turbine object class or anywhere else in the code. Its set at [line 76](https://github.com/WISDEM/FLORIS/blob/master/floris/turbine.py#L76) in Turbine.py.

**Comment by jrannoni** [comment]
It has not been incorporated in the code, but it could be used if you don't have a Cp/Ct table and rely only on the axial induction factor.

**Comment by rafmudaf** [comment]
@jrannoni to avoid confusion in developing a turbine model, do you mind if I remove that until its required?

**Comment by rafmudaf** [comment]
closed by #36
